TOP=../..
DIST=${TOP}/dist
THISDIR=installers/Darwin
OS := $(shell uname -s)

build:
	@echo "done in ${THISDIR}"

clean:
	@echo "done in ${THISDIR}"

test:
	@echo "done in ${THISDIR}"

package:
	@mkdir -p ${TOP}/dist2/simq
	@cp macdispintall.sh ${TOP}/dist2/simq
	@mkdir -p ${DIST}/simq
	@cp macinstall.sh "${DIST}/simq/"
	@echo "done in ${THISDIR}"
