#!/bin/bash

CONFIG_FILE="/usr/local/simq/simd/simdconf.json5"
SIMD_DIR="/var/lib/simd"
LOG_FILE="/tmp/postinstall.log"

exec > >(tee -a "$LOG_FILE") 2>&1
echo "-----------------------------------------------------------------------------"
echo "Starting postinstall script"

# Ensure that we have the simd user and group...
# Ensure that we have the simd user and group...
if id "simd" &>/dev/null; then
    echo "User 'simd' already exists."
else
    echo "Creating user 'simd'..."
    next_uid=$(dscl . -list /Users UniqueID | awk '{uid[$2]=1} END {for (i=501; i<600; i++) if (!uid[i]) {print i; exit}}')
    sudo dscl . -create /Users/simd
    sudo dscl . -create /Users/simd UserShell /usr/bin/false
    sudo dscl . -create /Users/simd RealName "SIMD Service User"
    sudo dscl . -create /Users/simd UniqueID "$next_uid"
    sudo dscl . -create /Users/simd PrimaryGroupID "$next_uid"
    sudo dscl . -create /Users/simd NFSHomeDirectory /var/empty
    sudo dscl . -passwd /Users/simd "Foolme123"
    sudo dscl . -append /Groups/wheel GroupMembership simd
fi

# Ensure the group 'simd' exists and set the correct GID
if ! dscl . -list /Groups PrimaryGroupID | grep -q "simd"; then
    echo "Creating group 'simd' with GID $next_gid..."
    next_gid=$(dscl . -list /Groups PrimaryGroupID | awk '{gid[$2]=1} END {for (i=1000; i<60000; i++) if (!gid[i]) {print i; exit}}')
    sudo dscl . -create /Groups/simd
    sudo dscl . -create /Groups/simd PrimaryGroupID "$next_gid"
    sudo dscl . -append /Groups/simd GroupMembership simd
else
    echo "Group 'simd' already exists."
    next_gid=$(dscl . -read /Groups/simd PrimaryGroupID | awk '{print $2}')
fi

# Update PrimaryGroupID for user 'simd' to match group 'simd'
echo "Updating PrimaryGroupID for user 'simd' to match group 'simd'..."
sudo dscl . -create /Users/simd PrimaryGroupID "$next_gid"

# Ensure /var/lib/simd exists
if [ ! -d "$SIMD_DIR" ]; then
    echo "Creating $SIMD_DIR..."
    sudo mkdir -p "$SIMD_DIR"
    sudo chown -R simd:simd "$SIMD_DIR"
    sudo chmod 755 "$SIMD_DIR"
fi

# Set the owner of the simd files to the simd user
echo "Changing ownership of /usr/local/simq/simd and /usr/local/simq/bin/psq..."
sudo chown -R simd:simd /usr/local/simq

# Get system information
CPUS=$(sysctl -n hw.ncpu)
MEMORY=$(sysctl -n hw.memsize)
MEMORY_GB=$(echo "scale=0; $MEMORY / (1024^3)" | bc)
CPU_ARCH=$(uname -m)

# Create the config file
echo "Creating config file $CONFIG_FILE..."
cat <<EOF > "$CONFIG_FILE"
{
    "CPUs": $CPUS,
    "Memory": "${MEMORY_GB}GB",
    "CPUArchitecture": "$CPU_ARCH",
    "MaxSimulations": 1,
    "SimdSimulationsDir": "/var/lib/simd",
    "DispatcherURL": "http://192.168.5.100:8250/"
}
EOF

echo "Configuration file created at $CONFIG_FILE"
