TOP=../..
DIST=${TOP}/dist
THISDIR=installers/Linux
OS := $(shell uname)

build:
	@echo "done in ${THISDIR}"

clean:
	@echo "done in ${THISDIR}"

test:
	@echo "done in ${THISDIR}"

package:
	@echo "done in ${THISDIR}"
